import { existsSync, mkdirSync, writeFileSync, appendFileSync, chmodSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

const PRE_COMMIT_HOOK_CONTENT = `#!/bin/sh
# Vet — AI Output Verification
# Auto-generated by "vet init"
# Run verification on staged changes before commit

if command -v vet > /dev/null 2>&1; then
  vet verify --quiet
  if [ $? -ne 0 ] && [ $? -ne 3 ]; then
    echo ""
    echo "  ✗ Vet verification failed. Use --no-verify to skip."
    exit 1
  fi
fi
`

const DEFAULT_CONFIG = {
  checks: {
    hallucination: true,
    security: true,
    style: true,
  },
  severity: {
    hallucination: 'error',
    security: 'error',
    style: 'warning',
  },
  files: {
    include: ['**/*.{ts,js,tsx,jsx,mjs,cjs}'],
    exclude: [
      '**/*.test.*',
      '**/*.spec.*',
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/.git/**',
    ],
  },
}

export function initCommand() {
  const cwd = process.cwd()

  const vetDir = join(cwd, '.vet')
  if (!existsSync(vetDir)) {
    mkdirSync(vetDir, { recursive: true })
    console.log('  ✓ Created .vet/ directory')
  } else {
    console.log('  ℹ .vet/ directory already exists')
  }

  const configPath = join(vetDir, 'config.json')
  if (!existsSync(configPath)) {
    writeFileSync(configPath, JSON.stringify(DEFAULT_CONFIG, null, 2), 'utf-8')
    console.log('  ✓ Created .vet/config.json')
  } else {
    console.log('  ℹ .vet/config.json already exists')
  }

  const gitDir = join(cwd, '.git')
  if (!existsSync(gitDir)) {
    console.log('  ⚠ Not a git repository. Skipping pre-commit hook.')
    return
  }

  const hooksDir = join(gitDir, 'hooks')
  const hookPath = join(hooksDir, 'pre-commit')

  if (!existsSync(hooksDir)) {
    mkdirSync(hooksDir, { recursive: true })
  }

  if (!existsSync(hookPath)) {
    writeFileSync(hookPath, PRE_COMMIT_HOOK_CONTENT, 'utf-8')
    chmodSync(hookPath, 0o755)
    console.log('  ✓ Pre-commit hook installed')
  } else {
    console.log('  ℹ Pre-commit hook already exists. Merge manually if needed.')
    console.log(`    File: ${hookPath}`)
  }

  const gitignorePath = join(cwd, '.gitignore')
  if (existsSync(gitignorePath)) {
    const content = readFileSync(gitignorePath, 'utf-8')
    if (!content.includes('.vet/')) {
      appendFileSync(gitignorePath, '\n.vet/\n')
      console.log('  ✓ Added .vet/ to .gitignore')
    }
  }

  console.log('')
  console.log('  ❯ Vet is ready!')
  console.log('')
  console.log('  Next steps:')
  console.log('    1. Stage your changes: git add .')
  console.log('    2. Commit: git commit')
  console.log('    3. Vet will verify AI-generated code automatically')
  console.log('')
}
